// Generated by CoffeeScript 1.7.1
(function() {
  var fetchRooms, token;

  token = '';

  $(function() {
    var options, t;
    options = {
      valueNames: ['user', 'message_content'],
      plugins: [ListFuzzySearch()]
    };
    t = new List('thread', options);
    return '#searchbox'.on('change', function(e) {
      var terms;
      terms = '#searchbox'.value();
      return t.fuzzySearch.search(terms);
    });
  });

  fetchRooms = function(callback) {
    return $.ajax('https://api.hipchat.com/v1/rooms/list', {
      async: false,
      success: callback
    });
  };

}).call(this);
